export const PACKAGE_VERSION = "@agencer/usage-accountant/0.1.0-alpha.0";

export const SUB_METERS = [
  "FACT_RECALL",
  "FACT_EXTRACTION",
  "FACT_EXTRACTION_CRITIC",
  "INTENT_CLASSIFIER",
  "ENGAGEMENT_CLASSIFIER",
  "RADAR_CLASSIFIER",
  "FILLER_GENERATION",
  "BRAIN_OPUS",
  "BRAIN_SONNET",
  "BRAIN_HAIKU",
  "TTS_CARTESIA",
  "STT_DEEPGRAM",
  "FINETUNE_TOGETHER",
  "LIVEKIT_BANDWIDTH",
] as const;
